bind 127.0.0.1 -::1
protected-mode yes
port 6379
daemonize yes
ignore-warnings ARM64-COW-BUG
supervised no
pidfile /data/data/com.termux/files/home/parts-erp/data/run/redis.pid
logfile /data/data/com.termux/files/home/parts-erp/data/logs/redis.log
dir /data/data/com.termux/files/home/parts-erp/data/redis
appendonly yes
appendfsync everysec
save 900 1
save 300 10
